// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqweuijjxystdpfszxet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxd2V1aWpqeHlzdGRwZnN6eGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MzMyMjcsImV4cCI6MjA1MDUwOTIyN30.ApXocOS0G3IJS-p-sAWSgMWeB9qMr-8uqzwJ6fys5PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);